--- 
id: proxycontract
name: プロキシ型コントラクト
summary: This tutorial gives a short introduction of the web3.js library, querying the block number
level: 3
tags: 
  - Remix
  - Solidity
  - Code Patterns
steps:
  - name: 1. プロキシ型コントラクトの利点
    path: 1_Why
  - name: 2. 作成方法
    path: 2_How
  - name: 3. Delegatecall
    path: 3_Delegatecall
  - name: 4. 一般的なサンプル
    path: 4_Generic_proxy_example
  - name: 5. テスト
    path: 5_Test
  - name: 6. ストレージ問題
    path: 6_Storage_Problem
  - name: 7. リンク
    path: 7_links